import = [
    "~/.config/alacritty/themes/themes/falcon.toml"
]

[window]

dimensions = { columns = 80, lines = 40 }
decorations = "None"
padding = { x = 5, y = 5 }

[font]

normal = { family = "Lilex Nerd Font", style="Regular"}
size = 12

